### PR TITLE
Set OwnerReferences for generated cm

### PR DESCRIPTION
**Pull request by clyang82**
https://github.com/observatorium/operator/issues/10

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Nice, any way we can quickly test it in unit test? 🤗

**Comment by bwplotka** [comment]
I would be happy to add test in separate PR 🤗 

Maybe premature merge, but I think we can iterate @squat

**Comment by clyang82** [comment]
Thanks @bwplotka Let me find time to add test for it.

**Comment by squat** [comment]
This does not seem like the right way to go and in fact I think this is kind of confusing for the user. The Owner Reference should point to the receive controller, not the owner of the statefulset IMO. If the statefulset is deleted, then the controller should delete the generated configmap but the configmap definitely does not belong to the process that created the statefulset. It is literally created and thus owned by a different controller.

**Comment by bwplotka** [comment]
Sorry for pre-merge than

**Comment by bwplotka** [comment]
https://github.com/observatorium/thanos-receive-controller/compare/master...revert-59-set_owner?expand=1

**Comment by clyang82** [comment]
@squat I agree with your point. the configmap is created by the receive controller. so the owner of configmap is the receive controller. Do we have another cases to have different owner for receive controller and statefulset? Do we need to watch the statefulset to delete the configmap if the sts is deleted?

**Comment by squat** [comment]
yes exactly, we should delete configmaps when sts are deleted. we don't do that today but we absolutely should. that would be how we clean things up.

**Pull request merged**
